config/routes.rb
Booklist::Application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  resources :messages
 
  get "pages/faq"
  get "pages/about" 
  devise_for :users
  resources :posts
   resources :users
  
  get "conversations/trash"

  get '/index' => 'posts#local'

  
   
    get '/gadgets' => 'posts#gadgets'
    get '/localgadgets'  => 'posts#localgadgets'
  
  get '/services' => 'posts#services'
  get '/localservices' => 'posts#localservices'
  
  get '/computers' => 'posts#computers'
  get '/localcomputers' => 'posts#localcomputers'
  
  get '/electronics' => 'posts#electronics'
  get '/localelectronics' => 'posts#localelectronics'
  
  get '/gear' => 'posts#gear'
  get '/localgear' => 'posts#localgear'
  
  get '/books' => 'posts#books'
  get '/localbooks' => 'posts#localbooks'
  
       
 
  
  
  

  
  resources :comments, :only => [:create, :destroy]

  root 'posts#index'
  

 

  

  
 

  
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
  
  
end
  

   
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
      def create
        @comment_hash = params[:comment]
        @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
        # Not implemented: check to see whether the user has permission to create a comment on this object
        @comment = Comment.build_from(@obj, current_user, @comment_hash[:body])
        if @comment.save
          render :partial => "comments/comment", :locals => { :comment => @comment }, :layout => false, :status => :created
        else
          render :js => "alert('error saving comment');"
        end
      end
  
  def destroy
      @comment = Comment.find(params[:id])
      if @comment.destroy
        render :json => @comment, :status => :ok
      else
        render :js => "alert('error deleting comment');"
      end
    end
  
  end

app/views/comments/_comment.html.erb
  <hr/>
  <%= link_to "×", comment_path(comment), :method => :delete, :remote => true, :confirm => "Are you sure you want to remove this comment?", :disable_with => "×", :class => 'close' %>
  <h4>
    <%= comment.user.username %>
    <small>
      <%= comment.updated_at %>
    </small>
  </h4>
  <p>
    <%= comment.body %>
  </p>

app/views/comments/_form.html.erb
 <%= simple_form_for comment, :remote => true do |f| %>
    <%= f.input :body, :input_html => { :rows => "2" }, :label => false %>
    <%= f.input :commentable_id, :as => :hidden, :value => comment.commentable_id %>
    <%= f.input :commentable_type, :as => :hidden, :value => comment.commentable_type %>
    <%= f.button :submit, :class => "btn btn-primary", :disable_with => "Submitting…" %>
  <% end %>
  

app/views/comments/show.html.erb
  <div id= "faq">
       <h2><%= @user.username %></h2>
    
      <h2>Comments</h2>
      <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
      <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
    </div>
  


  