config/routes.rb
Booklist::Application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  resources :messages
 
  get "pages/faq"
  get "pages/about" 
  devise_for :users
  resources :posts
   resources :users
  
  get "conversations/trash"

  get '/index' => 'posts#local'

  
   
    get '/gadgets' => 'posts#gadgets'
    get '/localgadgets'  => 'posts#localgadgets'
  
  get '/services' => 'posts#services'
  get '/localservices' => 'posts#localservices'
  
  get '/computers' => 'posts#computers'
  get '/localcomputers' => 'posts#localcomputers'
  
  get '/electronics' => 'posts#electronics'
  get '/localelectronics' => 'posts#localelectronics'
  
  get '/gear' => 'posts#gear'
  get '/localgear' => 'posts#localgear'
  
  get '/books' => 'posts#books'
  get '/localbooks' => 'posts#localbooks'
  
       
 
  
  
  

  
  resources :comments, :only => [:create, :destroy]

  root 'posts#index'
  

 

  

  
 

  
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
  
  
end
  

   
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  helper_method :mailbox, :conversation

  
    def index
    @conversations ||= current_user.mailbox.inbox.all
  
  end

  
  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
  redirect_to conversation
end
  
  def trashbin     
    @trash ||= current_user.mailbox.trash.all  
  end
  
  def trash  
    conversation.move_to_trash(current_user)  
    redirect_to :conversations 
  end 
  
  def untrash  
    conversation.untrash(current_user) 
    redirect_to :back 
  end
  
  def empty_trash  
    current_user.mailbox.trash.each do |conversation|   
      conversation.receipts_for(current_user).update_all(:deleted => true)
  end
 redirect_to :conversations
    end
  
  
  private
 
def mailbox
 @mailbox ||= current_user.mailbox
end
 
def conversation
 @conversation ||= mailbox.conversations.find(params[:id])
end
 
def conversation_params(*keys)
 fetch_params(:conversation, *keys)
end
 
def message_params(*keys)
 fetch_params(:message, *keys)
end
 
def fetch_params(key, *subkeys)
 params[key].instance_eval do
   case subkeys.size
   when 0 then self
   when 1 then self[subkeys.first]
   else subkeys.map{|k| self[k] }
   end
 end

  
  
end
 end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<style>
  body { background: #f5f8fa; }
</style>

<div id="page" class="main_wrapper clearfix">
    
	<div id="faq">
    
<% @conversations.each do |conversation| %>
 
    <h1><%= link_to conversation.subject, conversation %></h1>
    <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %>
   
    <%= link_to '<i id="awesomered" class="fa fa-times fa-2x"></i>'.html_safe, {:controller => "conversations", :action => "trash", :id => conversation.id}, :title=> "Move to Trash", :method=>'post' %> 
   
    
<% end %> 
    
    <% if @conversations.blank? %>
    <h1>no messages</h1>
     <% end %>
    <br /><br /><br /><br /><br /><br /><br />
    <h1><%= link_to '<i class="fa fa-trash-o"></i> trash'.html_safe, trashbin_conversations_path %> </h1>
  </div>
  </div>
 

app/views/conversations/show.html.erb
<style>
  body { background: #f5f8fa; }
  
  li {list-style-type:none;}
  
</style>

<div id="page" class="main_wrapper clearfix">
    
	<div id="faq">
    
    <h2><%= conversation.subject %></h2>
 
   
<% conversation.participants.each do |participant| %>
    
 <% if participant != current_user %>
     <h2 style="font-size: 1.5em"> 
  <%= participant.username %></h2>
 <% end %>
<% end %>
    <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>
    <div class="column-center" style="padding: 5px; margin-top: -10px; margin-bottom: 15px;">
 <% message = receipt.message %>
 <%= message.sender.username %>
    <p><%= simple_format h message.body %></p>
 
    <i>Sent <%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %></i>
   
<% end %>
    </div>    
<%= render 'messages/form', conversation: conversation %>
    
  </div> 

app/views/conversations/trash.html.erb
<% @trash.each do |conversation| %>
 


<%= link_to conversation.subject, conversation %>
<%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %>
<%= link_to "Move to Inbox", {:controller => "conversations", :action => "untrash", :id => conversation.id}, :title=> "Move to Inbox", :method=>'post' %>
<% end %>

app/views/conversations/trashbin.html.erb
<div id="page" class="main_wrapper clearfix">
<div id="faq">
 
<% @trash.each do |conversation| %>
 
  <h1><%= link_to conversation.subject, conversation %></h1>
<%= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p") %>

 <%= link_to '<i class="fa fa-inbox"></i> move to inbox'.html_safe, {:controller => "conversations", :action => "untrash", :id => conversation.id}, :title=> "Move to Inbox", :method=>'post' %>
  <hr>
<% end %>
</div>  
</div>  