config/routes.rb
Booklist::Application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  resources :messages
 
  get "pages/faq"
  get "pages/about" 
  devise_for :users
  resources :posts
   resources :users
  
  get "conversations/trash"

  get '/index' => 'posts#local'

  
   
    get '/gadgets' => 'posts#gadgets'
    get '/localgadgets'  => 'posts#localgadgets'
  
  get '/services' => 'posts#services'
  get '/localservices' => 'posts#localservices'
  
  get '/computers' => 'posts#computers'
  get '/localcomputers' => 'posts#localcomputers'
  
  get '/electronics' => 'posts#electronics'
  get '/localelectronics' => 'posts#localelectronics'
  
  get '/gear' => 'posts#gear'
  get '/localgear' => 'posts#localgear'
  
  get '/books' => 'posts#books'
  get '/localbooks' => 'posts#localbooks'
  
       
 
  
  
  

  
  resources :comments, :only => [:create, :destroy]

  root 'posts#index'
  

 

  

  
 

  
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
  
  
end
  

   
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
 
  
  
  validates :price, :numericality => {:only_integer => true}
  searchable do
    text :title
    text :author 
    text :course
    text :school
    text :email
    text :description
    text :price
    text :category
    integer :id
    time :updated_at
    
    
    
    string :school #notice, facet fields must be string, just add the field from above and diplicate it as string if text
   
  
   # ensure tha t a user_id is present
 # validates :user_id, presence: true
  end
  # ensure that title is present and at least 10 chars long
  validates :title, length: { minimum: 1 }, presence: true
   CATEGORY = ["BOOKS", "ELECTRONICS", "GADGETS", "COMPUTERS", "GEAR", "SERVICES"]
  
  
  
end
 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  


 

  # GET /posts
  # GET /posts.json
  def index
   
    @search = Post.search do #Post.search do
      fulltext params[:search]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
    @posts = @search.results
  end

 
  
  
  def local
    
    @search = Post.search do #Post.search do
       fulltext params[:search]         
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index  
  end
  
  
  
  def gadgets
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localgadgets
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
  
  
  def services
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localservices
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
  
  
  def books
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localbooks
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
  
  
  def electronics
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localelectronics
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
  
  
  def gear
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localgear
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
      
  def computers
    
    @search = Post.search do #Post.search do
      fulltext params[:category]
      
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
       end
       @posts = @search.results   
    render :index
  end
  
 
  def localcomputers
    @search = Post.search do #Post.search do
      fulltext params[:category] 
      with(:school, current_user.school)
      paginate :page => params[:page], :per_page => 20 
      order_by(:updated_at, :desc)
      end
       @posts = @search.results   
    render :index
  end    
  
 
  
  

  # GET /posts/1
  # GET /posts/1.json
  def show
  end
  
 
  
  
  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
   
    @post = Post.new(post_params) 
    @post.email = current_user.username
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    
   if current_user.username == @post.email 
    @post.destroy
      respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      end
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :course, :school, :price, :category, :description)
    end
  
  
  
  
  
  

  
  
  
 
  
end

app/views/posts/_form.html.erb
<br />
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="login-area" style="margin-top: 0px;">

		<div id="login-main">
			<center>
				<div id="login-error">
									</div>
			</center>
			<div id="slide-stage">
				<div id="login-panel">
 <div class="field">
   <%= hidden_field_tag :user_id, current_user.id %>
   
</div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "fruute-input", :size => 29 %>
  </div>
  <div class="field">
    <%= f.label :author, "author/brand" %><br>
    <%= f.text_field :author, :class => "fruute-input", :size => 29  %>
  </div>
  <div class="field">
    <%= f.label :course, "course or model" %><i> leave blank if none</i><br>
    <%= f.text_field :course, :class => "fruute-input", :size => 29 %>
  </div> 
          
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(Post::CATEGORY), {:prompt => "Select Category"}, :class => "dropdown", :style => "width:200px;" %>
          </div>    
     <div class="field">
       <%= f.label :school %><i> near you...</i><br />
       <%= f.select :school, options_for_select(User::SCHOOLS), {:prompt => "Select a School"}, :class => "dropdown", :style => "width:200px;"  %>
   </div>
          
          
          
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "fruute-input", :size => 29 %>
  </div>
          
      <div style="margin-left:240px; margin-top: -250px;  padding: 10px; padding-left: 20px;">     
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "fruute-input", :style => " width: 500px; height: 200px;" %>
  </div>
          
          
        
        <br /><br />
          
  <div class="actions">
    <%= button_tag(type: 'submit', class: "new-button", style: "width: 224px; height: 50px; ") do %>
 <i class="fa fa-location-arrow"></i>
     <% end %>     
   <!-- <%= f.submit :id => "submit-login", :class => "new-button" %>-->
  </div>
<% end %>
      
          </div>
       
        </div>
      </div>
    </div>
   </div>

app/views/posts/edit.html.erb
 <style>
  #formsite
  {
     margin-top: -5%;
  }
</style>
<div id="samples_wrapper" class="main_wrapper">
  <div id="formsite">
  <h1>edit post</h1>
  </div>
<div id="main_wrap" class="main_wrapper">






<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

  </div>

app/views/posts/index.html.erb
     

<div id="main" class="container" style="min-width: 1160px; margin-left: auto; ">
<div class="main_wrapper">   
<div id="main">
        <div class="streamCategory">
          <ul id="navlist">
              
            <li><%= link_to "books", :controller => "posts", :action => "books", :category => "books", :style => "color: gray;"  %> </li>
              <li><%= link_to "gadgets", :controller => "posts", :action => "gadgets", :category => "gadgets" , :style => "color: gray;" %> </li>
              <li><%= link_to "services", :controller => "posts", :action => "services", :category => "services", :style => "color: gray;"  %> </li>
              <li><%= link_to "gear", :controller => "posts", :action => "gear", :category => "gear" , :style => "color: gray;" %> </li>
              <li><%= link_to "computers", :controller => "posts", :action => "computers", :category => "computers" , :style => "color: gray;" %> </li>
              <li><%= link_to "electronics", :controller => "posts", :action => "electronics", :category => "electronics" , :style => "color: gray;" %> </li>
             
              
            </ul>
        
          
          </div>
  <br /><br />
        <div class="column-center" >
       
          
          <h1 style="background: #8fa2ae; color: #fff;">
            posts</h1>
           <br />
       
        <% @posts.each do |post| %>
          
     
      <%= link_to post do %>
          <div id="streamline" style="margin-top: -2px;">

             ~<%=  post.email %>
            <br /><br />
    <h1 style="font-size: 160%;"><%= post.title %></h1>
    <i class="fa fa-map-marker fa-lg" style="margin-right: 5px; margin-left: 5px;"></i>  <%= post.school %>  <div style="float: right; text-align: left; margin-right: 20px;"> <i class="fa fa-usd fa-lg"></i><%= post.price %></div> 
    
          </div>
   
        
<% end %>
          
    <% end %>
             
           <%= will_paginate @posts %>
          
   
        </div>
       
   
   
           
  
      
  <div class="column-right" style="margin-top: 0px;">
   
    <h1 style=" background: #8fa2ae; color: #fff;">stream</h1>
    <br />
   
       <div id="streamline">
    <h1 style="font-size: 140%;">coming soon!</h1>
        </div>
   
        </div>
   
  </div></div>
  <!--end main_wrap--></div>

   

app/views/posts/new.html.erb
 <style>
  #formsite
  {
 
     margin-top: -5%;
     margin-bottom: -30px;
  }
</style>


<div id="main" class="container">
  

   <br /><br />
   <h1 style="font-size: 2.5em; float: left;">new post</h1>   
      <br />
     
  
 
   
<%= render 'form' %>

  <br />
</div>


  

app/views/posts/show.html.erb
<style>
  #formsite
  {
     width: 100px;
     margin-right: 10px;
    
  }
   
  body { background: #f5f8fa; }

</style>
<!--
<div id="main_wrap" class="main_wrapper">
  <div id="formsite">
-->
  

<div class="main_wrapper" style="padding-bottom: 5px; padding-left: 10px; padding-top: 5px;  border: 1px solid  #e1e8ed; border-radius: 5px;  margin-top: 40px; min-height: 600px; background: white;">
  <div id="main" >
<p id="notice"><%= notice %></p>
  
  <h1 style="font-size: 1.5em; margin-top: -40px;">
  <strong>posted by</strong>
   
      <%= link_to @post.email, user_path(@post.user_id), :style => " border: 1px solid  #e1e8ed; border-radius: 5px; background:  #abcde4; color: white; " %>
    </h1>
  <hr>
  <h1> <%= word_wrap(@post.title, :line_width => 8) %></h1>
  <strong><%= @post.author %></strong><br />
  <hr style="width:100%;">
  <strong>course</strong><br />
  <h1 style="font-size: 1.5em"><%= @post.course %></h1>


<strong>category</strong><br />
  <h1 style="font-size: 1.5em"><%= @post.category %></h1>
    
    
  <strong>school</strong><br />
  <h1 style="font-size: 1.5em"><%= @post.school %></h1>


  <strong>price</strong><br />
  <h1 style="font-size: 1.5em"><%= @post.price %></h1>


    <br />
  <div style="margin-left:330px; margin-top: -155px; border-left: 1px solid #c8ccd3; padding: 5px; padding-left: 20px;">
  <h1>description</h1>
<h1 style="font-size: 1.5em"><%= word_wrap(@post.description, :line_width => 4) %></h1>
 

  <br />
  <i> posted on <%= @post.created_at.strftime("%a, %m/%e/%Y %I:%M %p") %></i><br /><br />
   

  
  
   <%= link_to '<i class="fa fa-reply"></i>'.html_safe, new_message_path(:user => @post.email), :class => "new-button" %>
<!--%= render 'messages/form', conversation: conversation % -->
   </div>
   </div>
   
    