config/routes.rb
Booklist::Application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  resources :messages
 
  get "pages/faq"
  get "pages/about" 
  devise_for :users
  resources :posts
   resources :users
  
  get "conversations/trash"

  get '/index' => 'posts#local'

  
   
    get '/gadgets' => 'posts#gadgets'
    get '/localgadgets'  => 'posts#localgadgets'
  
  get '/services' => 'posts#services'
  get '/localservices' => 'posts#localservices'
  
  get '/computers' => 'posts#computers'
  get '/localcomputers' => 'posts#localcomputers'
  
  get '/electronics' => 'posts#electronics'
  get '/localelectronics' => 'posts#localelectronics'
  
  get '/gear' => 'posts#gear'
  get '/localgear' => 'posts#localgear'
  
  get '/books' => 'posts#books'
  get '/localbooks' => 'posts#localbooks'
  
       
 
  
  
  

  
  resources :comments, :only => [:create, :destroy]

  root 'posts#index'
  

 

  

  
 

  
  resources :messages do
  member do
    post :new
  end
end
resources :conversations do
  member do
    post :reply
    post :trash
    post :untrash
  end
 collection do
    get :trashbin
    post :empty_trash
 end
  
  
end
  

   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head class="home">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <title>Booklist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
<%= javascript_include_tag "application" %>
 
  <!-------------------------------------------------------------------------------------------------------------------------------------------------->


  

<style>
h2 span { 
     
    color: #66757f;
    
    
    
} 
  
  
  #picframe {
    
    
    margin-left: -50px;
    
    float: left;
   
    margin-top: 4px;
  }
  
 
</style>





<!--------------------------------------------------------------------------------------------------------------------------------------------------->
  


  <div class="global-nav" data-section-term="top_nav" style=" position: fixed; z-index: 20; 
     
                                                             
                                                            
    opacity: 0.2;
    -ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=50)';
    filter: alpha(opacity=80);
    -moz-opacity: 0.80;
    -khtml-opacity: 0.8;
    opacity: 0.8;
                                                               
                                                             min-width: 1190px;
                                                             margin-top: -48px;
                                                             
                                                            
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
                                                             border-bottom: 1px solid #e1e8ed;"
       
       >
    <div class="global-nav-inner" >
      <div class="container">


          
      
          
         

            
        <div role="navigation" style="display: inline-block;">
              <ul class="nav js-global-actions" id="global-actions" style=" margin-top: 4px;">
               <li> 
                
      <%= link_to '<i class="fa fa-home fa-3x"></i>'.html_safe,  posts_path %>
                        
        
                  </li> 
                <li>
                 <% unless current_page?(new_post_path) %>
          <%= link_to '<i class="fa fa-pencil-square-o fa-3x"></i>'.html_safe, new_post_path %>
         <% end %>
                </li>
                <li>
         <% if user_signed_in? %>
         <% unless current_page?(conversations_path) %>
                  <%= link_to '<i class="fa fa-inbox fa-3x"></i>'.html_safe, conversations_path %>
         <% end %>
         <% end %>
                </li>
                
              </ul>   
          
          
          <% unless current_page?(index_path) %>
          <div class="pull-left" style="display: inline-block;"> <div role="search">      
       <%= form_tag posts_path, :method => :get do %>
       <%= text_field_tag :search, params[:search], id: 'search' , autofocus: false ,:placeholder => "search",:class =>'fruute-input', :size => 30 %>
            </div>
            <button type="submit" id="mybutton" >
              <i class="fa fa-search fa-lg" style = "color: white;"></i>                     
            </button>
           <% end %>
            <% end %>
            
            <% if current_page?(index_path) %>
          <div class="pull-left" style="display: inline-block;"> <div role="search">      
       <%= form_tag index_path, :method => :get do %>
       <%= text_field_tag :search, params[:localsearch], id: 'search' , autofocus: false ,:placeholder => "search",:class =>'fruute-input', :size => 30 %>
            </div>
            <button type="submit" id="mybutton" >
              <i class="fa fa-search fa-lg" style = "color: white;"></i>                     
            </button>
            <% end %>
            <% end %>
          
           
 
           
              </div>
    
        </div>
       
     
          
               <% unless user_signed_in? %>
            
<ul class = "nav right-actions" style="float: right; display: inline-block;">  
                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                        <li style ="margin-right: 250px; margin-top: -4px;";>
 
                  <%= f.email_field :email, autofocus: true, :class => "fruute-input sign-in", :style => "width: 150px;", :placeholder => "email"  %>
     
           
      
                </li>
                <li style="margin-left: 165px; margin-top: -32px; margin-bottom: -32px;">
                  <%= f.password_field :password, autocomplete: "off",  :id => 'user-password', :class => "fruute-input sign-in", :style => "width: 150px;", :placeholder => "password"  %>
                </li>
                
     <li>
  <%= button_tag(type: 'submit', class: "new-buttonLogin") do %>
          
                 <i class="fa fa-sign-in"></i>
  </li>
  
            
          </ul>
           
        <% end %>  
                
                <% end %>
                
                <% end %>
                
                <% if user_signed_in? %>
          <ul class = "nav right-actions" style="float: right; display: inline-block;">
       <li>
       <%= link_to '<i class="fa fa-cog fa-2x"></i>'.html_safe, edit_user_registration_path %> 
                </li>
                <li>
        <%= link_to('<i class="fa fa-power-off fa-2x"></i>'.html_safe, destroy_user_session_path, :method => :delete) %> 
                </li>
     
     
            </ul>
      
     <% end %>
       

      




      
  
  </div>  
       </div> 
  
  
     
    </div>
   
   <% if current_page?(user_session_path) %>
    
    
    

  

  
    <div id="main" class="container" style="min-width: 1160px; margin-top: 50px; margin-bottom: -50px; padding-top: 20px;">  
      
     
      
      
    
      <h2 style="padding-top: 15px;"><span>a local stream of buyers and sellers based on college locations, buy stuff, sell stuff</span></h2>
      
  </div>
      
  
    
  </div>
    <% end %>
 
    
     <div class="ProfileCanopy-navBar">
  <div id="main" class="container" style="min-width: 1160px; margin-left:auto; margin-top: -10px; "> 
   
    <% if user_signed_in? %>
    <div class="user-info-menu" style="margin-left: 350px; position: relative;">
     
        
      <%= link_to user_path(current_user) do %>
      <div class="user-info">
 
        <div id="main">
        
        <h2 style="margin-top: -40px; margin-bottom: -8px; padding: 0px; font-size: 185%;"><%= current_user.firstname %>
        <%= current_user.lastname %></h2>
        <p style="margin-bottom: -3px;">~<%= current_user.username %></p><i class="fa fa-map-marker fa-lg"></i><%= current_user.school %>
        
       </div>
        
  
    </div>
      <% end %>
    </div>
 
   <div class="user-info-menu" >
    
      
      <ul id="navlist" style="minimum-width: 1190px;" >
        <li style="padding-right: 155px; text-align: center;">POSTS<br /><a><%= current_user.posts.count :conditions => {:user_id => current_user.id} %></a></li>
        <li style="padding-right: 155px; text-align: center;">STREAMS<br /><a>290</a></li>
        <li style="padding-right: 155px; text-align: center;">STREAMERS<br /><a>3294</a></li>
        <li style="padding-right: 155px; text-align: center;">RATING<br /><a>*****</a></li>
      </ul>
        
      
    </div>
    
     
  </div>
  </div>
  <% end %>
  

  
 
  
<!-- FROM HERE UP TWITTER -->

  </head>
  
<body class="">

  <br />
<div id="main_wrapper">
 <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
<%= yield %>
  </div>
 
  </body>
  <br />  <br />  <br />  <br />

  <footer id="footer">
    
	<ul>
		
    <li><%= mail_to "delossantos.franklin@gmail.com", "contact", subject: "the startup" %></li>
		
    <li><%= link_to "faq", pages_faq_path %></li>
         
    <li><%= link_to "about", pages_about_path %></li>
		<li>all rights reserved 2014 - Franklin De Los Santos</li>
		<li class="last">made in los angeles</li>
	</ul>
	
</footer>
</html>